// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200419214339_ActivityCreate")]
    partial class ActivityCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1.0,
                            Email = "nishank.net@gmail.com",
                            FirstName = "User1 FirstName",
                            LastName = "User1 LastName",
                            Password = "Pentium@1",
                            UID = new Guid("bcae147e-4424-4a20-a76a-f351bfe19a82"),
                            Username = "User1"
                        },
                        new
                        {
                            Id = 2.0,
                            Email = "test@gmail.com",
                            FirstName = "User2 FirstName",
                            LastName = "User2 LastName",
                            Password = "Pentium@2",
                            UID = new Guid("cf3259d1-8204-4d0c-b41b-54b0aaa7baa9"),
                            Username = "User2"
                        },
                        new
                        {
                            Id = 3.0,
                            Email = "test2@gmail.com",
                            FirstName = "User3 FirstName",
                            LastName = "User3 LastName",
                            Password = "Pentium@3",
                            UID = new Guid("1f31f8b1-9958-4d73-aeff-410152a07c3a"),
                            Username = "User3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
