// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1.0,
                            Email = "nishank.net@gmail.com",
                            FirstName = "User1 FirstName",
                            LastName = "User1 LastName",
                            Password = "Pentium@1",
                            UID = new Guid("c3904252-9664-440d-b063-a88ad939c823"),
                            Username = "User1"
                        },
                        new
                        {
                            Id = 2.0,
                            Email = "test@gmail.com",
                            FirstName = "User2 FirstName",
                            LastName = "User2 LastName",
                            Password = "Pentium@2",
                            UID = new Guid("c38f09b5-0313-4b74-bae4-b547c893af76"),
                            Username = "User2"
                        },
                        new
                        {
                            Id = 3.0,
                            Email = "test2@gmail.com",
                            FirstName = "User3 FirstName",
                            LastName = "User3 LastName",
                            Password = "Pentium@3",
                            UID = new Guid("3506dc0e-c4ac-463c-ad9f-6a7a59e37868"),
                            Username = "User3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
